spring.application.name=rating-and-review-service

spring.config.import=env.properties

spring.datasource.url=jdbc:sqlite:app.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true